// <auto-generated />
using System;
using MangaBot.Infra.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaBot.Infra.Migrations
{
    [DbContext(typeof(MangaBotContext))]
    partial class MangaBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MangaBot.Domain.Model.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("execucao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbLog");
                });

            modelBuilder.Entity("MangaBot.Domain.Model.Manga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotaldeCapitulos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbManga");
                });

            modelBuilder.Entity("MangaBot.Domain.Model.MangaUsuario", b =>
                {
                    b.Property<int>("MangaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasIndex("MangaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbMangaUsuario", (string)null);
                });

            modelBuilder.Entity("MangaBot.Domain.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("apikey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomecompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("numero_phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbUsuario");
                });

            modelBuilder.Entity("MangaBot.Domain.Model.MangaUsuario", b =>
                {
                    b.HasOne("MangaBot.Domain.Model.Manga", "Manga")
                        .WithMany()
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaBot.Domain.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
